// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Obracore.Data;

#nullable disable

namespace Obracore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251105205319_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Obracore.Models.CustoEtapa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<DateTime>("DtRegistro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dt_registro");

                    b.Property<int>("EtapaId")
                        .HasColumnType("int")
                        .HasColumnName("etapas_id");

                    b.Property<decimal>("Valor")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("EtapaId");

                    b.ToTable("custos_etapas", (string)null);
                });

            modelBuilder.Entity("Obracore.Models.CustoObra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<DateTime>("DtRegistro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dt_registro");

                    b.Property<int?>("EtapaId")
                        .HasColumnType("int")
                        .HasColumnName("etapas_id");

                    b.Property<int>("ObraId")
                        .HasColumnType("int")
                        .HasColumnName("obras_id");

                    b.Property<decimal>("Valor")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("EtapaId");

                    b.HasIndex("ObraId");

                    b.ToTable("custos_obra", (string)null);
                });

            modelBuilder.Entity("Obracore.Models.Documento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CaminhoArquivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("caminho_arquivo");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime?>("DataEdicao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_edicao");

                    b.Property<int>("EnviadoPorId")
                        .HasColumnType("int")
                        .HasColumnName("enviado_por_id");

                    b.Property<int>("ObraId")
                        .HasColumnType("int")
                        .HasColumnName("obras_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("tipo");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.HasIndex("EnviadoPorId");

                    b.HasIndex("ObraId");

                    b.ToTable("documentos", (string)null);
                });

            modelBuilder.Entity("Obracore.Models.DocumentoEtapa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Caminho")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("caminho");

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dt_criacao");

                    b.Property<int>("EtapaId")
                        .HasColumnType("int")
                        .HasColumnName("etapas_id");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.HasIndex("EtapaId");

                    b.ToTable("documentos_etapa", (string)null);
                });

            modelBuilder.Entity("Obracore.Models.DocumentoObra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Caminho")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("caminho");

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dt_criacao");

                    b.Property<int>("ObraId")
                        .HasColumnType("int")
                        .HasColumnName("obras_id");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.HasIndex("ObraId");

                    b.ToTable("documentos_obras", (string)null);
                });

            modelBuilder.Entity("Obracore.Models.Etapa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<DateTime?>("DtFim")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dt_fim");

                    b.Property<DateTime?>("DtFimPrevista")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dt_fim_prevista");

                    b.Property<DateTime?>("DtInicio")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dt_inicio");

                    b.Property<string>("EtapasCol")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("etapascol");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome");

                    b.Property<int>("ObraId")
                        .HasColumnType("int")
                        .HasColumnName("obras_id");

                    b.Property<int?>("Ordem")
                        .HasColumnType("int")
                        .HasColumnName("ordem");

                    b.Property<string>("Status")
                        .HasMaxLength(1)
                        .HasColumnType("char(1)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ObraId");

                    b.ToTable("etapas", (string)null);
                });

            modelBuilder.Entity("Obracore.Models.Financa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime?>("DataEdicao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_edicao");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_registro");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descricao");

                    b.Property<int?>("EtapaId")
                        .HasColumnType("int")
                        .HasColumnName("etapas_id");

                    b.Property<int>("ObraId")
                        .HasColumnType("int")
                        .HasColumnName("obras_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("tipo");

                    b.Property<decimal>("Valor")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("EtapaId");

                    b.HasIndex("ObraId");

                    b.ToTable("financas", (string)null);
                });

            modelBuilder.Entity("Obracore.Models.Obra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dt_criacao");

                    b.Property<DateTime?>("DtEdicao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dt_edicao");

                    b.Property<DateTime?>("DtFim")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dt_fim");

                    b.Property<DateTime?>("DtFimPrevista")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dt_fim_prevista");

                    b.Property<DateTime?>("DtInicio")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dt_inicio");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("nome");

                    b.Property<string>("StatusObra")
                        .HasMaxLength(1)
                        .HasColumnType("char(1)")
                        .HasColumnName("status_obra");

                    b.HasKey("Id");

                    b.ToTable("obras", (string)null);
                });

            modelBuilder.Entity("Obracore.Models.Perfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("perfis", (string)null);
                });

            modelBuilder.Entity("Obracore.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dt_criacao");

                    b.Property<DateTime?>("DtEdicao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dt_edicao");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("senha");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Obracore.Models.UsuarioObra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ObraId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ObraId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("usuarios_obras", (string)null);
                });

            modelBuilder.Entity("Obracore.Models.UsuarioPerfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PerfilId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PerfilId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("usuario_perfil", (string)null);
                });

            modelBuilder.Entity("Obracore.Models.CustoEtapa", b =>
                {
                    b.HasOne("Obracore.Models.Etapa", "Etapa")
                        .WithMany("CustosEtapa")
                        .HasForeignKey("EtapaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Etapa");
                });

            modelBuilder.Entity("Obracore.Models.CustoObra", b =>
                {
                    b.HasOne("Obracore.Models.Etapa", "Etapa")
                        .WithMany()
                        .HasForeignKey("EtapaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Obracore.Models.Obra", "Obra")
                        .WithMany("CustosObra")
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Etapa");

                    b.Navigation("Obra");
                });

            modelBuilder.Entity("Obracore.Models.Documento", b =>
                {
                    b.HasOne("Obracore.Models.Usuario", "EnviadoPor")
                        .WithMany()
                        .HasForeignKey("EnviadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Obracore.Models.Obra", "Obra")
                        .WithMany()
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnviadoPor");

                    b.Navigation("Obra");
                });

            modelBuilder.Entity("Obracore.Models.DocumentoEtapa", b =>
                {
                    b.HasOne("Obracore.Models.Etapa", "Etapa")
                        .WithMany("DocumentosEtapa")
                        .HasForeignKey("EtapaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Etapa");
                });

            modelBuilder.Entity("Obracore.Models.DocumentoObra", b =>
                {
                    b.HasOne("Obracore.Models.Obra", "Obra")
                        .WithMany("DocumentosObras")
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Obra");
                });

            modelBuilder.Entity("Obracore.Models.Etapa", b =>
                {
                    b.HasOne("Obracore.Models.Obra", "Obra")
                        .WithMany("Etapas")
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Obra");
                });

            modelBuilder.Entity("Obracore.Models.Financa", b =>
                {
                    b.HasOne("Obracore.Models.Etapa", "Etapa")
                        .WithMany()
                        .HasForeignKey("EtapaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Obracore.Models.Obra", "Obra")
                        .WithMany()
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Etapa");

                    b.Navigation("Obra");
                });

            modelBuilder.Entity("Obracore.Models.UsuarioObra", b =>
                {
                    b.HasOne("Obracore.Models.Obra", "Obra")
                        .WithMany("UsuariosObras")
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Obracore.Models.Usuario", "Usuario")
                        .WithMany("UsuariosObras")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Obra");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Obracore.Models.UsuarioPerfil", b =>
                {
                    b.HasOne("Obracore.Models.Perfil", "Perfil")
                        .WithMany("UsuarioPerfis")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Obracore.Models.Usuario", "Usuario")
                        .WithMany("UsuarioPerfis")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Obracore.Models.Etapa", b =>
                {
                    b.Navigation("CustosEtapa");

                    b.Navigation("DocumentosEtapa");
                });

            modelBuilder.Entity("Obracore.Models.Obra", b =>
                {
                    b.Navigation("CustosObra");

                    b.Navigation("DocumentosObras");

                    b.Navigation("Etapas");

                    b.Navigation("UsuariosObras");
                });

            modelBuilder.Entity("Obracore.Models.Perfil", b =>
                {
                    b.Navigation("UsuarioPerfis");
                });

            modelBuilder.Entity("Obracore.Models.Usuario", b =>
                {
                    b.Navigation("UsuarioPerfis");

                    b.Navigation("UsuariosObras");
                });
#pragma warning restore 612, 618
        }
    }
}
